In [3]:
import yfinance as yf
import pandas as pd

# Download Apple stock data
df = yf.download(
    "AAPL",
    start="2020-01-01",
    end="2025-01-01"
)

df.head()

[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open     Volume
Ticker           AAPL       AAPL       AAPL       AAPL       AAPL
Date
2020-01-02  72.333870  72.394078  71.091176  71.344047  135480400
2020-01-03  71.630638  72.389257  71.406666  71.563205  146322800
2020-01-06  72.201416  72.239950  70.503554  70.754021  118387200
2020-01-07  71.861839  72.466322  71.642681  72.211041  108872000
2020-01-08  73.017838  73.318877  71.565621  71.565621  132079200

In [4]:
print(df.shape)

df.info()

df.describe()

(1258, 5)
<class 'pandas.DataFrame'>
DatetimeIndex: 1258 entries, 2020-01-02 to 2024-12-31
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, AAPL)   1258 non-null   float64
 1   (High, AAPL)    1258 non-null   float64
 2   (Low, AAPL)     1258 non-null   float64
 3   (Open, AAPL)    1258 non-null   float64
 4   (Volume, AAPL)  1258 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 59.0 KB

Price         Close         High          Low         Open        Volume
Ticker         AAPL         AAPL         AAPL         AAPL          AAPL
count   1258.000000  1258.000000  1258.000000  1258.000000  1.258000e+03
mean     151.377786   152.899566   149.680871   151.223470  9.057103e+07
std       41.851999    41.992363    41.629303    41.795805  5.324438e+07
min       54.163692    55.160690    51.324789    55.059301  2.323470e+07
25%      126.279110   127.397101   124.278541   125.724387  5.546825e+07
50%      149.968597   151.709765   148.037187   149.788875  7.628335e+07
75%      175.902027   177.452433   174.337241   175.708215  1.077425e+08
max      257.375580   258.448740   255.994420   256.550862  4.265100e+08

In [14]:
df.to_csv("../data/raw/apple_stock.csv")