In [7]:
import yfinance as yf
import pandas as pd

# Download Apple stock data
df = yf.download(
    "AAPL",
    start="2020-01-01",
    end="2025-01-01"
)

df.head()

[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open     Volume
Ticker           AAPL       AAPL       AAPL       AAPL       AAPL
Date
2020-01-02  72.333862  72.394070  71.091169  71.344039  135480400
2020-01-03  71.630638  72.389257  71.406666  71.563205  146322800
2020-01-06  72.201393  72.239927  70.503531  70.753999  118387200
2020-01-07  71.861862  72.466345  71.642704  72.211064  108872000
2020-01-08  73.017822  73.318862  71.565606  71.565606  132079200

In [8]:
print(df.shape)

df.info()

df.describe()

(1258, 5)
<class 'pandas.DataFrame'>
DatetimeIndex: 1258 entries, 2020-01-02 to 2024-12-31
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, AAPL)   1258 non-null   float64
 1   (High, AAPL)    1258 non-null   float64
 2   (Low, AAPL)     1258 non-null   float64
 3   (Open, AAPL)    1258 non-null   float64
 4   (Volume, AAPL)  1258 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 59.0 KB

Price         Close         High          Low         Open        Volume
Ticker         AAPL         AAPL         AAPL         AAPL          AAPL
count   1258.000000  1258.000000  1258.000000  1258.000000  1.258000e+03
mean     151.377786   152.899566   149.680871   151.223470  9.057103e+07
std       41.851999    41.992363    41.629303    41.795805  5.324438e+07
min       54.163696    55.160694    51.324793    55.059305  2.323470e+07
25%      126.279102   127.397091   124.278543   125.724387  5.546825e+07
50%      149.968628   151.709742   148.037194   149.788897  7.628335e+07
75%      175.902042   177.452413   174.337230   175.708235  1.077425e+08
max      257.375549   258.448710   255.994390   256.550832  4.265100e+08

In [9]:
df.to_csv("../data/raw/apple_stock.csv")

In [11]:
print(df.shape)
df.info()
df.describe()
df.head()
df.isnull().sum()

(1258, 5)
<class 'pandas.DataFrame'>
DatetimeIndex: 1258 entries, 2020-01-02 to 2024-12-31
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, AAPL)   1258 non-null   float64
 1   (High, AAPL)    1258 non-null   float64
 2   (Low, AAPL)     1258 non-null   float64
 3   (Open, AAPL)    1258 non-null   float64
 4   (Volume, AAPL)  1258 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 59.0 KB

Price   Ticker
Close   AAPL      0
High    AAPL      0
Low     AAPL      0
Open    AAPL      0
Volume  AAPL      0
dtype: int64